name: Process disclosure

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - staging
    paths:
      - "bounties/**"

defaults:
  run:
    working-directory: tools/process-disclosure

jobs:
  generate-diff:
    name: Generate diff
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.generate-diff.outputs.diff }}
    if: github.event.label.name == 'disclosure'
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: node-setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: restore-node-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - id: dependency-install
        name: Install npm dependencies
        run: npm ci
      - id: generate-diff
        name: Generate the diff
        env:
          BASE_COMMIT_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_COMMIT_SHA: ${{ github.sha }}
        run: node ./generate-diff.js
  contains-only-one-bounty:
    name: Contains only one bounty
    needs: generate-diff
    runs-on: ubuntu-latest
    outputs:
      bounty_dir: ${{ steps.contains-only-bounty-files.outputs.bounty_dir }}
    if: github.event.label.name == 'disclosure'
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: node-setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: restore-node-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - id: dependency-install
        name: Install npm dependencies
        run: npm ci
      - id: contains-only-bounty-files
        name: Contains only bounty files
        env:
          DIFF: ${{ needs.generate-diff.outputs.diff }}
        run: node ./contains-only-one-bounty.js
  contains-only-bounty-files:
    name: Contains only bounty files
    needs: generate-diff
    runs-on: ubuntu-latest
    if: github.event.label.name == 'disclosure'
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: node-setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: restore-node-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - id: dependency-install
        name: Install npm dependencies
        run: npm ci
      - id: contains-only-bounty-files
        name: Contains only bounty files
        env:
          DIFF: ${{ needs.generate-diff.outputs.diff }}
        run: node ./contains-only-bounty-files.js
  contains-only-new-bounty-files:
    name: Contains only new bounty files
    needs: generate-diff
    runs-on: ubuntu-latest
    if: github.event.label.name == 'disclosure'
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: node-setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: restore-node-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - id: dependency-install
        name: Install npm dependencies
        run: npm ci
      - id: contains-only-bounty-files
        name: Contains only bounty files
        env:
          DIFF: ${{ needs.generate-diff.outputs.diff }}
        run: node ./contains-only-new-bounty-files.js
  contains-a-valid-vulnerability-json:
    name: Contains a valid vulnerability.json
    needs: contains-only-one-bounty
    runs-on: ubuntu-latest
    if: github.event.label.name == 'disclosure'
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: node-setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: restore-node-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - id: dependency-install
        name: Install npm dependencies
        run: npm ci
      - id: contains-a-valid-vulnerability-json
        name: Contains a valid vulnerability.json
        env:
          BOUNTY_DIR: ${{ needs.contains-only-one-bounty.outputs.bounty_dir }}
        run: node ./contains-a-valid-vulnerability-json.js
  contains-a-valid-readme-md:
    name: Contains a valid README.md
    needs: contains-only-one-bounty
    runs-on: ubuntu-latest
    if: github.event.label.name == 'disclosure'
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: node-setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: restore-node-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - id: dependency-install
        name: Install npm dependencies
        run: npm ci
      - id: contains-a-valid-readme-md
        name: Contains a valid README.md
        env:
          BOUNTY_DIR: ${{ needs.contains-only-one-bounty.outputs.bounty_dir }}
        run: node ./contains-a-valid-readme-md.js
  contains-a-valid-directory:
    name: Directory format matches vulnerability.json values
    needs: 
      [ 
        contains-only-one-bounty, 
        contains-a-valid-vulnerability-json 
      ]
    runs-on: ubuntu-latest
    if: github.event.label.name == 'disclosure'
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: node-setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: restore-node-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - id: dependency-install
        name: Install npm dependencies
        run: npm ci
      - id: contains-a-valid-directory
        name: Directory format matches vulnerability.json values
        env:
          BOUNTY_DIR: ${{ needs.contains-only-one-bounty.outputs.bounty_dir }}
        run: node ./directory-matches-package-name.js
  merge-disclosure:
    name: Merge disclosure
    needs:
      [
        contains-only-one-bounty,
        contains-only-bounty-files,
        contains-only-new-bounty-files,
        contains-a-valid-vulnerability-json,
        contains-a-valid-readme-md,
      ]
    runs-on: ubuntu-latest
    if: github.event.label.name == 'disclosure'
    steps:
      - id: auto-pull-request-merge
        name: Merge disclosure
        uses: KeisukeYamashita/auto-pull-request-merge@v1
